blank_issues_enabled: false
contact_links:
  - name: "Bug Report"
    url: "/Amna-Hassan04/Serenity-Guide/issues/new?assignees=&labels=bug&template=bug_report.md&title="
    about: "Report a bug or issue with the project"
  - name: "Feature Request"
    url: "/Amna-Hassan04/Serenity-Guide/issues/new?assignees=&labels=enhancement&template=feature_request.md&title="
    about: "Suggest a new feature or enhancement"
