name: Check Screenshot in PR

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Check if screenshot is attached
        id: check_screenshot
        run: |
          # Fetch the PR body (description) using jq
          PR_BODY=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")

          # Log the PR body for debugging (you can remove this later)
          echo "PR BODY: $PR_BODY"

          # Check if the PR body contains a GitHub-hosted image URL or image extensions (png, jpg, jpeg, gif)
          if echo "$PR_BODY" | grep -E "https://github.com/.+/assets/|\.png|\.jpg|\.jpeg|\.gif"; then
            echo "Screenshot found!"
          else
            echo "No screenshot found! Please attach a screenshot to your PR."
            exit 1  # Fail the workflow if no screenshot is found
          fi
